"""Converting between the HeadRush wire value and the value the unit shows.

#33, #126. The table is `config/headrush_tapers.json`, generated by
tools/build_headrush_tapers.py out of the vendor's own web editor.

WHY THIS IS A SEPARATE MODULE FROM THE REGISTRY

`devices/headrush/registry.py` is the DEVICE describing itself: schema in,
lookup out, and it refuses to convert precisely because the device publishes an
opaque curve id and no formula. That refusal is still correct about the API and
is left alone. This module is a different kind of knowledge, read out of the
editor the unit serves, and it carries `provenance` and `api_readable` the way
`topology.py` does so that nothing downstream can present a converted number as
something the unit said.

Keeping them apart is the whole point. A caller that has only the registry
cannot convert and knows it. A caller that reaches for this one has to name
where the maths came from.

HOW THE FORMULAS GOT HERE

Not by reading the minified JavaScript and retyping the maths. `Db` and
`AllenHeathFaderVolume` are exactly the shapes that survive a typo and still
return plausible numbers. The generator runs the vendor's own code under node
over a grid of 990 points and commits the results, and the Python below is
checked against those vectors. So a mistake in this file fails a test rather
than becoming a confidently wrong dB value.

Six readings taken off a Core's screen agree with the whole chain to the digit.
That is corroboration on one block, not proof across 302 objects, and the
warning in the artifact says so.
"""
from __future__ import annotations

import json
import math
import struct
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

CONFIG = Path(__file__).resolve().parent.parent.parent / "config"
TAPERS = CONFIG / "headrush_tapers.json"

#: The vendor's dispatch is `(t.algo ? table[t.algo] : void 0) ?? table[0]`, so
#: a parameter with no algo AND one carrying 0 both land on Linear.
LINEAR = 0


class UnknownTaper(LookupError):
    """An algo id this firmware's editor does not define."""


class NotConvertible(ValueError):
    """The curve is defined and this particular value has no finite image."""


def _f32(value: float) -> float:
    """JavaScript's Math.fround, which the vendor applies on the way to wire."""
    return struct.unpack("f", struct.pack("f", value))[0]


def _clamp(value: float, lo: float, hi: float) -> float:
    return min(max(value, lo), hi)


# JavaScript's Math.log/Math.log10 return -Infinity at zero and NaN below it,
# where Python's raise ValueError. The vendor's curves rely on that: Volume at
# wire 0 is log10(0), and the editor renders the -Infinity as the string
# "-inf" rather than crashing. Mirroring the vendor here keeps the divergence
# out of the curves, so `_finite` can turn it into one typed refusal in one
# place instead of each curve growing its own guard.

def _js_log10(value: float) -> float:
    if value == 0:
        return -math.inf
    return math.log10(value) if value > 0 else math.nan


def _js_log(value: float) -> float:
    if value == 0:
        return -math.inf
    return math.log(value) if value > 0 else math.nan


# --- the curves, one per id, transcribed then CHECKED against the vendor's
# --- own output rather than trusted. See the module docstring.

def _lin_out(x, lo, hi):        return (hi - lo) * x + lo
def _lin_in(v, lo, hi):         return (v - lo) / (hi - lo)

def _db_out(x, lo, hi):         return lo + 2 * x * -lo if x <= 0.5 else hi * (x - 0.5) * 2
def _db_in(v, lo, hi):          return (v - lo) / (2 * -lo) if v <= 0 else 0.5 + v / (2 * hi)

def _vol_out(x, lo, hi):        return 20 * _js_log10(x)
def _vol_in(v, lo, hi):         return math.pow(10, 0.05 * v)

def _tbs_out(x, lo, hi):
    n = 2 * x - 1
    return n * n * (-hi if n < 0 else hi)

def _tbs_in(v, lo, hi):
    n = abs(v) / hi
    n = 1.0 if n > 1 else math.sqrt(n)
    return 0.5 + 0.5 * (-n if v < 0 else n)

def _sq_out(x, lo, hi):         return lo + (hi - lo) * x * x
def _sq_in(v, lo, hi):
    clamped = _clamp(v, lo, hi)
    return 0.0 if hi == lo else math.sqrt((clamped - lo) / (hi - lo))

def _exp_out(x, lo, hi):        return lo * math.exp(_js_log(hi / lo) * x)
def _exp_in(v, lo, hi):         return _js_log(v / lo) / _js_log(hi / lo)

_MIXER = 0.044282303954338874
def _mix_out(x, lo, hi):        return _MIXER * (math.exp(4.515 * x) - 1)
def _mix_in(v, lo, hi):         return _js_log(v / _MIXER + 1) / 4.515

def _h3v_out(x, lo, hi):        return hi + 20 * _js_log10(max(x, 1e-10))
def _h3v_in(v, lo, hi):
    if v <= -200:
        return 0.0
    return hi if v > hi else math.pow(10, 0.05 * (v - hi))

_AH_REF = math.pow(10, 0.05 * -14)      # yf(-14)
_AH_E = -14 / 0.75
_AH_S = _AH_REF / 0.25
def _ah_out(x, lo, hi):
    return math.pow(10, 0.05 * ((1 - x) * _AH_E)) if x > 0.25 else x * _AH_S
def _ah_in(v, lo, hi):
    return 1 - (20 * _js_log10(v) / _AH_E) if v > _AH_REF else v / _AH_S

def _h3r_out(x, lo, hi):        return 145.0 if x > _f32(0.99) else (0.45 + x) / (1 - x)
def _h3r_in(v, lo, hi):         return 1.0 if v > 144 else (v - 0.45) / (1 + v)


#: id -> (to_display, to_wire). DelayRatio (3) is in the vendor's enum and in
#: NEITHER table, so its dispatch falls through to Linear; it is absent here
#: for the same reason and `curve_for` resolves it explicitly.
CURVES = {
    0:  (_lin_out, _lin_in),
    1:  (_db_out,  _db_in),
    2:  (_vol_out, _vol_in),
    4:  (_tbs_out, _tbs_in),
    5:  (_sq_out,  _sq_in),
    6:  (_exp_out, _exp_in),
    7:  (_mix_out, _mix_in),
    8:  (_h3v_out, _h3v_in),
    9:  (_ah_out,  _ah_in),
    10: (_h3r_out, _h3r_in),
}


def snap_to_grid(display: float, grid: float) -> float:
    """The display value the unit settles on, given its published grid.

    THE PUBLISHED GRID IS A FLOAT32 AND MUST NOT BE USED LITERALLY. A grid the
    vendor wrote as 0.01 arrives as 0.009999999776482582, and snapping with
    that value lands just beside the mark the unit uses: it put a prediction
    for `Amp.TremSpeed` at 0.33299559354782104 where the Core holds
    0.33299562335014343. Recovering the decimal at float32's ~7 significant
    digits is what makes all eight pairs measured in #167 reproduce exactly.

    Lives here rather than in the adapter because the simulator needs the same
    arithmetic, and two copies of a calculation that was got wrong twice is
    two places for it to be got wrong again.
    """
    quantum = float(f"{grid:.7g}")
    return round(display / quantum) * quantum


@dataclass(frozen=True)
class TaperTable:
    """The eleven, plus where they came from. Provenance is not optional."""

    provenance: str
    api_readable: bool
    warning: str
    source: str
    names: dict[int, str]
    unimplemented: tuple[int, ...]

    def name(self, algo: int | None) -> str:
        return self.names[self.resolve(algo)]

    def resolve(self, algo: int | None) -> int:
        """Which curve actually runs for this id.

        `None` and `0` are both Linear, and so is any id the vendor's enum
        names but neither table implements, because that is what the vendor's
        own `?? table[0]` fallback does. An id outside the enum is NOT quietly
        given the same treatment: the firmware would be publishing something
        this table has never seen, and guessing Linear there could silently
        mis-scale every value of a parameter.
        """
        if algo is None or algo == LINEAR:
            return LINEAR
        # Membership of the vendor's enum is checked BEFORE the unimplemented
        # list. The other order let a corrupt artifact that listed an unknown
        # id as unimplemented turn the raise below into a silent linear scale,
        # which is the exact failure the raise exists to prevent.
        if algo not in self.names:
            raise UnknownTaper(
                f"normalizeAlgo {algo} is not one of the {len(self.names)} "
                f"this firmware's editor defines. The device is publishing a "
                f"curve this table has not seen; re-generate from the unit's "
                f"bundle rather than assuming linear.")
        if algo in self.unimplemented:
            return LINEAR
        return algo

    def to_display(self, wire: float, *, minimum: float, maximum: float,
                   algo: int | None = None) -> float:
        """The number the unit would show for this wire value."""
        out, _ = CURVES[self.resolve(algo)]
        return self._evaluate(out, wire, minimum, maximum, algo)

    def to_wire(self, display: float, *, minimum: float, maximum: float,
                algo: int | None = None) -> float:
        """The wire value for a number as the unit shows it.

        Rounded to float32, which is what the vendor does before sending.
        """
        _, into = CURVES[self.resolve(algo)]
        return _f32(self._evaluate(into, display, minimum, maximum, algo))

    def _evaluate(self, curve, given: float, lo: float, hi: float,
                  algo: int | None) -> float:
        """Run a curve, turning every non-answer into ONE typed refusal.

        Python and JavaScript disagree about arithmetic at the edges, and the
        vendor's curves sit on those edges. Measured against the committed
        vectors, the points with no number are `Exponential` on a range whose
        minimum is at or below zero, where `log(hi / lo)` divides by zero here
        and is Infinity or NaN there, and `Volume` at wire 0, where `log10(0)`
        raises here and is -Infinity there.

        NOT `H3ReverbTime`, which an earlier version of this docstring named.
        Its `(0.45 + x) / (1 - x)` never divides by zero, because the vendor
        guards it with `x > fround(0.99)` and returns 145 first, and this
        module carries the same guard. Independent review caught that, and it
        is written out rather than quietly corrected because the wrong version
        was the stated justification for catching ZeroDivisionError at all.

        Every one of these means the same thing, that the editor has no number
        to show and renders a special string instead, so they collapse to
        NotConvertible in one place rather than each curve growing a guard and
        one of them being forgotten. A test walks every reference vector and
        asserts this refuses at exactly the points the vendor cannot express a
        number for, no more and no fewer.

        The catch is deliberately WIDER than those points: it also covers a
        genuine mistake in a curve that happens to raise. A test pins the
        forward direction exactly, so on-grid such a mistake fails the
        comparison rather than hiding here.
        """
        try:
            value = curve(given, lo, hi)
        except (ZeroDivisionError, ValueError, OverflowError) as err:
            raise NotConvertible(
                f"taper {self.name(algo)} has no value at {given} on "
                f"{lo}..{hi}; the editor shows a special string here rather "
                f"than a number ({type(err).__name__})") from err
        if not math.isfinite(value):
            raise NotConvertible(
                f"taper {self.name(algo)} has no finite value at {given}; the "
                f"editor shows a special string here rather than a number")
        return value


@lru_cache(maxsize=1)
def load(path: Path | None = None) -> TaperTable:
    blob = json.loads((path or TAPERS).read_text())
    names = {int(k): v["name"] for k, v in blob["tapers"].items()}
    missing = sorted(set(names) - set(CURVES) - set(blob["unimplemented"]))
    if missing:
        raise UnknownTaper(
            f"the table names tapers {missing} that this module does not "
            f"implement. Regenerating the artifact without adding the curve "
            f"would convert them as linear, silently.")
    return TaperTable(
        provenance=blob["provenance"],
        api_readable=blob["api_readable"],
        warning=blob["warning"],
        source=blob["source"],
        names=names,
        unimplemented=tuple(blob["unimplemented"]),
    )
