#!/usr/bin/env python3
"""Map every HeadRush amp-model ordinal to the real amplifier it emulates.

    python tools/build_headrush_amp_models.py
    python tools/build_headrush_amp_models.py --catalog PATH --schema PATH

Same move as tools/build_amp_models.py did for the FM9 (#2) and
tools/build_cab_models.py for the cabs (#14): the planner should resolve "a
Bassman into a 4x10" to a real ordinal rather than guess at a model name.

WHY THIS LANDS BEFORE ANY HEADRUSH ADAPTER

Grounding data is device knowledge, not device code. It needs no adapter, no
device handle and none of the contract work in #109, which is why #33 put it
first. When an adapter arrives this is already here; if one never arrives,
this still documents what a second device's roster means.

THE SOURCE IS THE MANUFACTURER, WHICH IS UNUSUAL AND WORTH SAYING

`config/amp_models.json` is built from a community guide, so THIRD_PARTY_NOTICES
is careful about whose writing it is. This one is different: HeadRush publishes
what each of its models emulates, on its own product page, as a plain
attribution list. Those attributions are the manufacturer's own factual claims
about its own product. No prose, no tips, no third-party writing is involved,
so there is nothing here to reproduce that belongs to anyone else.

TWO INPUTS, BOTH ALREADY GENERATED BY SCRIPT

  catalog   the vendor's attribution list, scraped from headrushfx.com by
            @bschmalz81401's HeadrushRigBuilder and committed there
  schema    the DEVICE's own self-description, fetched from a unit over its
            HTTP API by the same project

Neither is hand written, which is the point. The catalog says what a model
emulates; the schema says which ORDINAL the device gives that model. Joining
them is what turns an attribution list into something a planner can send.

The join is by name, and it is close but not exact: the catalog uses the
vendor's marketing capitalisation while the device reports its own strings.
Normalising case and whitespace matches 50 of 53 HeadRush amps and 47 of 48
ReValver amps. The remainder are spelling differences, handled in OVERRIDES
below, and one genuine absence handled as an absence.

WHAT IS DELIBERATELY NOT HERE

A cross-map to the FM9 roster. Both catalogs name real amplifiers, so pivoting
one to the other looks like a small matter of string matching. It is not.
Measured against config/amp_models.json, exact matching after normalisation
finds 4 of 100, and fuzzy matching fills the gap with confident nonsense:

    Vox AC30 Top Boost   ~ Vox AC15 Top Boost    0.80
    Fender Dual Showman  ~ Fender Bassman        0.73
    Fender Princeton     ~ Fender Princeton Rvrb 0.82

Each of those is a different amplifier. A generated table that maps a player's
AC30 onto an AC15 is worse than no table, because it looks authoritative. If
cross-device translation is wanted it needs a human-confirmed mapping, and it
is its own piece of work.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "config" / "headrush_amp_models.json"

#: Where HeadrushRigBuilder keeps its two generated artifacts, if it is checked
#: out beside this repo. Both are overridable; neither is vendored here.
SIBLING = ROOT.parent / "HeadrushRigBuilder"
DEFAULT_CATALOG = SIBLING / "docs" / "device" / "model-catalog.json"
DEFAULT_SCHEMA = SIBLING / "src" / "lib" / "device-schema.generated.json"

#: block name -> the catalog category listing that block's models.
#: The parenthesised counts are the vendor's own and do not always match the
#: number of entries under the heading, so they are matched literally rather
#: than parsed: REVALVER AMP MODELS says 44 and lists 47.
BLOCKS = {
    "Amp": "HEADRUSH AMP MODELS (53)",
    "ReValver Amp": "REVALVER AMP MODELS (44)",
}

#: device string -> catalog string, where the two spell the same model
#: differently. Corrections go HERE, never in the generated JSON, so a
#: regeneration cannot silently drop them.
#: Verbatim oddities in the vendor's list that are NOT generator bugs, noted
#: here because the next reader will suspect they are:
#:   `68 Plexi EL84 Mod` is attributed to a "Super Lead Plexi (EL34 tubes mod)".
#:   EL84 in the model name, EL34 in the attribution. That is what the page
#:   says, and facts-only means it ships as published rather than corrected.
OVERRIDES = {
    "93 MS-30": "93 MS30",
    "05 Tangerine 30 Ch1": "05 Tangerine 30 Channel 1",
    "05 Tangerine 30 Ch2": "05 Tangerine 30 Channel 2",
}

#: Ordinals the device offers that the vendor's own catalog does not describe.
#: Recorded as unknown rather than inferred. `90 Michael ACM 900` follows the
#: naming convention of the models around it closely enough to tempt a guess,
#: and a guess is exactly what this project does not ship: the roster says
#: "unknowns stay unknown: nothing is invented".
UNATTRIBUTED = {
    "90 Michael ACM 900": "not described on the vendor's published model list",
}


def norm(s: str) -> str:
    """Case and whitespace only. Anything cleverer starts inventing matches."""
    return " ".join(s.lower().split())


def model_options(schema: dict, block: str) -> list[str]:
    """The ordinal-indexed model list the DEVICE publishes for one block.

    This is the staleness anchor. The device reports `Type` as an integer whose
    options are these strings in order, so entry N of this list is what
    ordinal N means on the unit. If a firmware update reorders the roster,
    every ordinal below moves with it and the committed names stop matching,
    which is what the test is for.
    """
    try:
        params = schema["blocks"][block]["params"]
    except KeyError:
        sys.exit(f"schema has no block {block!r}; is this a HeadRush schema?")
    # by NAME, not by label. These blocks are twins: `Type` and `Type2` both
    # carry label "Model" and today hold identical option lists, so matching
    # the label works by luck. `keyed_by` says Type, so key on Type.
    for p in params:
        if p.get("name") == "Type" and p.get("options"):
            return list(p["options"])
    sys.exit(f"block {block!r} publishes no Type parameter with options")


def build(catalog: dict, schema: dict) -> dict:
    entries = catalog.get("entries") or []
    amps: dict[str, dict] = {}
    unmatched: list[str] = []

    for block, category in BLOCKS.items():
        by_name = {norm(e["name"]): e for e in entries
                   if e.get("category") == category}
        if not by_name:
            sys.exit(f"catalog has no category {category!r}")

        rows: dict[str, dict] = {}
        for ordinal, device_name in enumerate(model_options(schema, block)):
            row = {"headrush": device_name}
            lookup = OVERRIDES.get(device_name, device_name)
            hit = by_name.get(norm(lookup))
            if hit:
                row["model"] = hit["inspiredBy"]
            elif device_name in UNATTRIBUTED:
                row["model"] = None
                row["unattributed"] = UNATTRIBUTED[device_name]
            else:
                unmatched.append(f"{block}[{ordinal}] {device_name!r}")
            rows[str(ordinal)] = row
        amps[block] = rows

    if unmatched:
        sys.exit("no catalog entry and no override for:\n  "
                 + "\n  ".join(unmatched)
                 + "\nAdd a spelling to OVERRIDES, or record a genuine absence "
                   "in UNATTRIBUTED. Do not guess the attribution.")

    described = sum(1 for rows in amps.values() for r in rows.values()
                    if r.get("model"))
    total = sum(len(rows) for rows in amps.values())
    return {
        "schema_version": 1,
        "device": "HeadRush",
        "content": "facts",
        "keyed_by": "block name, then the Model parameter's ordinal "
                    "(Amp.Type and 'ReValver Amp'.Type)",
        "source": catalog.get("source", "HeadRush published model list"),
        "source_generated_at": catalog.get("generatedAt"),
        "device_schema_source": schema.get("source"),
        "device_schema_generated_at": schema.get("generatedAt"),
        "generated_by": "tools/build_headrush_amp_models.py",
        "warning": "Generated file. Hand edits are lost on regeneration. "
                   "OVERRIDES in the generator is a SPELLING table for the "
                   "join key only: it cannot correct a wrong attribution, "
                   "because the attribution is the vendor's own words and "
                   "changing it would stop this being a record of what they "
                   "published. 'headrush' is the device's own Model option at "
                   "that ordinal and is what a future drift guard would "
                   "compare; nothing local verifies it today, because this "
                   "repo vendors no HeadRush roster (see fm9.grounding."
                   "UNGUARDABLE).",
        "counts": {"ordinals": total, "described": described,
                   "unattributed": total - described},
        "amps": amps,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG,
                    help="vendor attribution list (HeadrushRigBuilder)")
    ap.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA,
                    help="device self-description (HeadrushRigBuilder)")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args(argv)

    for path, what in ((args.catalog, "catalog"), (args.schema, "schema")):
        if not path.exists():
            sys.exit(f"{what} not found: {path}\n"
                     f"Both are generated artifacts of HeadrushRigBuilder; "
                     f"check it out beside this repo or pass --{what}.")

    built = build(json.loads(args.catalog.read_text()),
                  json.loads(args.schema.read_text()))
    args.out.write_text(json.dumps(built, indent=1, ensure_ascii=False) + "\n")
    c = built["counts"]
    print(f"wrote {args.out.relative_to(ROOT)}: {c['ordinals']} ordinals, "
          f"{c['described']} described, {c['unattributed']} unattributed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
